name: Deploy Subgraph

on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'True to bypass the check for changes'
        required: false
        type: boolean
  push:
    branches:
      - main
      - develop

jobs:
  paths:
    name: Path Filter
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'secured-finance-machine-user[bot]' }}
    outputs:
      subgraph: ${{ steps.changes.outputs.subgraph }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.extract_branch.outputs.branch }}
          filters: |
            subgraph:
              - 'src/**'
              - 'schema.graphql'
              - 'subgraph.yaml'
              - 'package.json'
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    needs: [paths]
    if: ${{ needs.paths.outputs.subgraph == 'true' || github.event.inputs.force_publish == 'true' }}
    steps:
      - run: echo "${{ needs.paths.outputs.subgraph }}"
      - run: echo "${{ needs.paths.outputs.client }}"
      - run: echo "${{ needs.paths.outputs.packages }}"
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy Subgraph
        id: deploy
        run: |
          npm run auth ${{secrets.GRAPH_ACCESS_TOKEN}}
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npm run update-subgraphrc staging
            version=$(cat deployment.json | jq -r .staging.version | tr -d '"')
            npm run generate:stg
            npm run deploy:stg ${version}
          else
            npm run update-subgraphrc development
            version=$(cat deployment.json | jq -r .development.version | tr -d '"')
            npm run generate:dev
            npm run deploy:dev ${version}
          fi
